config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, controllers: { registrations: "registrations" }

  get "/dashboard", to: "dashboard#index"
  resources :categories
  resources :transactions, controller: "financial_transactions"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :deleted_at }
  validates :budget, presence: true, numericality: { greater_than_or_equal_to: 0 }

  scope :active, -> { where(deleted_at: nil) }
end

app/models/financial_transaction.rb
# frozen_string_literal: true

class FinancialTransaction < ApplicationRecord
  belongs_to :category

  validates :description, :date, :category_id, presence: true
  validates :amount, presence: true,
                     numericality: { greater_than_or_equal_to: 0 }
  validates :transaction_type, presence: true, inclusion: { in: %w(W D R) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  before_action :authenticate_user!,
    unless: -> { request.controller_class == HomeController }

  private

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || dashboard_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # don't authenticate user on api calls
  skip_before_action :authenticate_user!, only: [:create, :destroy]

  def index
    render locals: {
      categories: Category.active
    }
  end

  def create
    category = Category.create(category_params)

    if category.persisted?
      render json: { category: category }
    else
      render status: 400, json: { messages: category.errors.messages }
    end
  end

  def destroy
    category = Category.find(params[:id])

    category.update(deleted_at: Time.current)

    render json: { category: category }
  end

  private

  def category_params
    params.require(:category).permit(:name, :budget)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/financial_transactions_controller.rb
class FinancialTransactionsController < ApplicationController
  def index
    render locals: {
      transactions: FinancialTransaction.all
    }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home"

  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_update_path_for(resource)
    edit_user_registration_path
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/categories/index.html.erb
<section>
  <%= react_component("Categories", props: { categories: categories, addUrl: categories_path }, prerender: false) %>
</section>

app/views/dashboard/index.html.erb
<section>
  <header>Graph</header>
  <p>
    This chart will show how much you've spent in each budget with an x axis
    of month, y axis of categories, and a line dictating where you are in the
    given month.
  </p>
  <p>
    over flow will be handled (hopefully) by displaying a red bar instead of a
    in progress bar with a note on how far over budget you are.
  </p>
</section>

app/views/financial_transactions/index.html.erb
<section>
  <%= react_component("Transactions", props: { transactions: transactions }, prerender: false) %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Centsible</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-controller="<%= controller_name %>">
    <% if alert %>
      <p class="notice error" data-dismiss>
        <%= alert %>
        <span onclick="dismiss()">&times;</span>
      </p>
    <% end %>
    <% if notice %>
      <p class="notice info" data-dismiss>
        <%= notice %>
        <span onclick="dismiss()">&times;</span>
      </p>
    <% end %>

    <main>
      <aside role="sidebar">
        <header>
          <h1>
            <%= link_to root_path do %>
              &cent;entsible
              <span>budget</span>
            <% end %>
          </h1>
        </header>
        <nav role="nav">
          <%= link_to "Dashboard", dashboard_path, class: "#{'active' if request.path == dashboard_path}" %>
          <%= link_to "Transactions", transactions_path, class: "#{'active' if request.path == '/transactions'}" %>
          <%#= link_to "Timeline", "#" %>
          <header>Settings</header>
          <%= link_to "Spending Categories", categories_path,
            class: "#{'active' if request.path == '/categories' }" %>
          <%= link_to "Profile", edit_user_registration_path,
            class: "#{'active' if request.path == edit_user_registration_path || request.path == user_registration_path}" %>
          <%#= link_to "Notifications", "#" %>

          <%# this absolutely needs to be at the bottom to style correctly %>
          <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
          <% end %>
        </nav>
      </aside>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Centsible</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-controller="<%= controller_name %>">
    <main>
      <header>
        <h1>
          <%= link_to root_path do %>
            &cent;entsible
            <span>budget</span>
          <% end %>
        </h1>
      </header>
      <section>
        <% if alert %>
          <p class="error"><%= alert %></p>
        <% end %>
        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% end %>

        <%= yield %>
      </section>
    </main>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Centsible</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-controller="<%= controller_name %>">
    <% if alert %>
      <p class="notice error" data-dismiss>
        <%= alert %>
        <span onclick="dismiss()">&times;</span>
      </p>
    <% end %>
    <% if notice %>
      <p class="notice info" data-dismiss>
        <%= notice %>
        <span onclick="dismiss()">&times;</span>
      </p>
    <% end %>

    <header>
      <h1>
        <%= link_to root_path do %>
          &cent;entsible
          <span>budget</span>
        <% end %>
      </h1>
      <nav>
        <% if user_signed_in? %>
          <%= link_to "Dashboard", dashboard_path %>
          <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path %>
        <% end %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>